name: Build Kivy APK

on: push: branches: - main workflow_dispatch: {}

jobs: android: name: Build Android APK runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install system dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y \
        python3-pip python3-setuptools git \
        autoconf libtool pkg-config zlib1g-dev unzip \
        default-jdk-headless

  - name: Install Buildozer & Cython
    run: |
      python -m pip install --upgrade pip
      pip install buildozer==1.4.2 Cython==0.29.33

  - name: Configure Android SDK & NDK
    uses: malinskiy/setup-android@v2
    with:
      api-level: 31
      build-tools: '31.0.0'
      ndk: '21.4.7075529'

  - name: Export Android environment variables
    run: |
      echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
      echo "PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV

  - name: Validate buildozer.spec
    run: |
      if [ ! -f buildozer.spec ]; then
        echo "Error: buildozer.spec not found. Run 'buildozer init' locally and commit it." >&2
        exit 1
      fi

  - name: Build APK (debug)
    run: |
      buildozer -v android debug

  - name: Upload APK artifact
    uses: actions/upload-artifact@v3
    with:
      name: MyKivyApp-APK
      path: bin/*.apk

